### PR TITLE
bump jasper dependencies

### PR DESCRIPTION
**Pull request by poum**
allow successful compile on Debian Buster

### CODE REVIEW

**Comment by kwoot** [comment]
Nice! I will review this very soon. Thanks!

**Review by kwoot — APPROVED** [review]
Works for me.

**Comment by tramseyer** [comment]
Displaying reports such as "Hours Worked Per Resource" do no longer work (Ubuntu 20.04 and 22.04) after this pull request:
```
HTTP ERROR 410
Problem accessing /zkau/view/z_gm7/oJ2Q69/rev/0/hoursWorkedPerWorkerReport.html. Reason:

    Failed to load /view/z_gm7/oJ2Q69/rev/0/hoursWorkedPerWorkerReport.html

Cause: 
net.sf.jasperreports.engine.JRException: Class not found when loading object from InputStream.
```

**Comment by kwoot** [comment]
Confirm bug.

**Pull request merged**
